SELECT V.VOTER_ID, V.NAME, C.CONSTITUENCY_NAME
FROM VOTER V, CONSTITUENCY C
WHERE V.CONSTITUENCY_ID=C.CONSTITUENCY_ID;

SELECT C.NAME, COUNT(V.VOTE_ID) AS TOTAL_VOTES
FROM CANDIDATE C, VOTE V
WHERE C.CANDIDATE_ID=V.CANDIDATE_ID
GROUP BY C.NAME;

DELETE FROM VOTE WHERE VOTER_ID=305;
DELETE FROM VOTER WHERE VOTER_ID=305;

CREATE VIEW CANDIDATE_VIEW2 AS
SELECT NAME, AGE, GENDER
FROM CANDIDATE;
SELECT * FROM CANDIDATE_VIEW2;

CREATE VIEW TOTAL_VOTERS2 AS
SELECT COUNT(*) AS TOTAL FROM VOTER;
SELECT * FROM TOTAL_VOTERS2;
