CREATE TABLE CONSTITUENCY(CONSTITUENCY_ID INT PRIMARY KEY,CONSTITUENCY_NAME VARCHAR(50),DISTRICT VARCHAR(50),STATE VARCHAR(50));

select * from CONSTITUENCY;

CREATE TABLE ADMIN(ADMIN_ID INT PRIMARY KEY,USERNAME VARCHAR(50),PASSWORD VARCHAR(50),NAME VARCHAR(50),EMAIL VARCHAR(50));

SELECT * FROM ADMIN;

CREATE TABLE PARTY(PARTY_ID INT PRIMARY KEY,PARTY_NAME VARCHAR(50),SYMBOL VARCHAR(50),LEADER_NAME VARCHAR(50));

SELECT * FROM PARTY;

CREATE TABLE VOTER(VOTER_ID INT PRIMARY KEY,NAME VARCHAR(50),DOB DATE,GENDER VARCHAR(10),PHONE VARCHAR(15),ADDRESS VARCHAR(100),CONSTITUENCY_ID INT,FOREIGN KEY(CONSTITUENCY_ID) REFERENCES CONSTITUENCY(CONSTITUENCY_ID));

SELECT * FROM VOTER;

CREATE TABLE CANDIDATE(CANDIDATE_ID INT PRIMARY KEY,NAME VARCHAR(50),AGE INT,GENDER VARCHAR(10),PARTY_ID INT,CONSTITUENCY_ID INT,FOREIGN KEY(PARTY_ID) REFERENCES PARTY(PARTY_ID),FOREIGN KEY(CONSTITUENCY_ID) REFERENCES CONSTITUENCY(CONSTITUENCY_ID));

SELECT * FROM CANDIDATE;

CREATE TABLE VOTE(VOTE_ID INT PRIMARY KEY,VOTER_ID INT,CANDIDATE_ID INT,VOTE_DATE DATE,FOREIGN KEY(VOTER_ID) REFERENCES VOTER(VOTER_ID),FOREIGN KEY(CANDIDATE_ID) REFERENCES CANDIDATE(CANDIDATE_ID));

SELECT * FROM VOTE;

